name: "Dismiss alerts"
description: 'Dismiss GitHub CodeScanning alerts that are marked as "suppressed" in SARIF'
inputs:
  sarif-id:
    description: "Identifier of the uploaded SARIF file"
    required: true
  sarif-file:
    description: "Path to the input SARIF file"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
